name: CI/CD for Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ayeshaabaloch849 }}  # Update with your Docker Hub username secret
          password: ${{ secrets.r5ND6^&A4XRz(ea }}  # Update with your Docker Hub password secret

      - name: Build and push first Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile1  # Specify your first Dockerfile
          push: true
          tags: ayeshaabaloch849/payment-service:latest  # Name of the first image

      - name: Build and push second Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile2  # Specify your second Dockerfile
          push: true
          tags: ayeshaabaloch849/order-service:latest  # Name of the second image

      - name: Build and push third Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile3  # Specify your third Dockerfile
          push: true
          tags: ayeshaabaloch849/menu-services:latest  # Name of the third image

        - name: Build and push second Docker image   
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile2  # Specify your second Dockerfile
          push: true
          tags: ayeshaabaloch849/inventory-service:latest  # Name of the second image
          
           - name: Build and push second Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile2  # Specify your second Dockerfile
          push: true
          tags: ayeshaabaloch849/customer-service:latest  # Name of the second image

